[package]
name = "kovert-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "kovert"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
kovert-core = { path = "../kovert-core" }
serde_json.workspace = true
tokio.workspace = true

[lints]
workspace = true

