[package]
name = "kovert-sensors"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
blake3.workspace = true
evdev.workspace = true
kovert-core = { path = "../kovert-core", version = "0.1.0" }
notify.workspace = true
tokio.workspace = true

[lints]
workspace = true
